name: Remote Deployment
on:
  push:
    branches:
      - main # Only trigger on main branch pushes

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Execute deployment via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -e # Exit immediately on error
            cd /home/support/web/workflowtoolstaging.godspeedoffers.com/public_html
            git pull
            git reset --hard origin/main
            composer install --no-interaction --no-dev --prefer-dist
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            npm run build
            sudo chown -R www-data:www-data /home/support/web/workflowtoolstaging.godspeedoffers.com/public_html/storage
            sudo chown -R www-data:www-data /home/support/web/workflowtoolstaging.godspeedoffers.com/public_html/bootstrap/cache
            sudo chmod -R 775 /home/support/web/workflowtoolstaging.godspeedoffers.com/public_html/storage
            sudo chmod -R 775 /home/support/web/workflowtoolstaging.godspeedoffers.com/public_html/bootstrap/cache

